# $Id: Makefile,v 1.13 2006/10/31 00:55:04 dme26 Exp $
#
# BOB Makefile

.phony: info election configPerms clear clean

files = AUTHORS COPYING INSTALL Makefile electionConfig.pm genElection.pl rollcheck.php vote.php
genLiveFiles = config.php vote.txt ballot.html .htaccess
genStubFiles = createtable.sql voters.sql printelection.sql

release = 0.5
archiveName = BOB$(release).tar.gz

info:
	# NOTE: You should edit electionConfig.pm before making the election target
	#
	# Targets:
	#
	# election: run the Perl script genElection.pl
	# clear: remove generated stub files (e.g. SQL import templates)
	# clean: remove all files generated by genElection.pl (including .htaccess)
	# archive: create a tar file of this directory
	# 

archive:	configPerms $(archiveName)

configPerms:
	chmod 664 AUTHORS COPYING INSTALL Makefile vote.php
	chmod 660 electionConfig.pm 
	chmod 750 genElection.pl 

election:
	./genElection.pl

$(archiveName): $(files)
	tar -zcvf $(archiveName) --exclude CVS --exclude *~ $(files)

clear:
	rm -f $(genStubFiles)

clean: clear
	rm -f $(genLiveFiles) *~ $(archiveName)
