# $Id: Makefile,v 1.10 2005/11/01 12:38:01 dme26 Exp $
#
# BOB Makefile

.phony: remove info election configPerms clean

files = AUTHORS COPYING INSTALL Makefile electionConfig.pm genElection.pl vote.php
genLiveFiles = secret.php vote.txt ballot.html
genStubFiles = createtable.sql voters.sql

release = 0.4
archiveName = BOB$(release).tar.gz

info:
	# NOTE: You should edit electionConfig.pm before making the election target
	#
	# Targets:
	#
	# election: run the Perl script genElection.pl
	# clean: remove generated stub files (e.g. SQL import templates)
	# remove: remove all files generated by genElection.pl
	# archive: create a tar file of this directory
	# 

archive:	configPerms $(archiveName)

configPerms:
	chmod 664 AUTHORS COPYING INSTALL Makefile vote.php
	chmod 660 electionConfig.pm 
	chmod 750 genElection.pl 

election:
	./genElection.pl

$(archiveName): $(files)
	tar -zcvf $(archiveName) --exclude CVS --exclude *~ $(files)

clean:
	rm -f $(genStubFiles)

remove: clean
	rm -f $(genLiveFiles) *~ $(archiveName)
