# $Id: Makefile 127 2007-02-20 15:39:15Z dme26 $
#
# BOB Makefile

.phony: info election configPerms rinse cleanall

files = AUTHORS COPYING INSTALL Makefile electionConfig.pm genElection.pl rollcheck.php vote.php BOB.php admin_checkvoter.php admin_checkcount.php admin_dump.php admin_results.php showvotes.php ballot.php
genLiveFiles = config.php vote.txt config.txt ballot.txt BOB.txt .htaccess
genStubFiles = createtable.sql voters.sql printelection.sql

release = 0.6c
archiveName = BOB$(release).tar.gz

info:
	# NOTE: You should edit electionConfig.pm before making the election target
	#
	# Targets:
	#
	# election: run the Perl script genElection.pl
	# rinse: remove generated stub files (e.g. SQL import templates)
	# cleanall: remove all files generated by genElection.pl (including .htaccess)
	# archive: create a tar file of this directory
	# 

archive:	configPerms $(archiveName)

configPerms:
	chmod 644 AUTHORS COPYING INSTALL Makefile rollcheck.php vote.php BOB.php ballot.php
	chmod 600 electionConfig.pm 
	chmod 700 genElection.pl 

election:
	./genElection.pl

$(archiveName): $(files)
	tar -zcvf $(archiveName) --exclude CVS --exclude *~ $(files)

rinse:
	rm -f $(genStubFiles)

cleanall: rinse
	rm -f $(genLiveFiles) *~ $(archiveName)
